version: '3'
services:
  web:
      build: .
      hostname: web
      command : "flask run"
      volumes:
        - .:/app
      ports:
        - "5000:5000"
      environment:
        FLASK_ENV : development
